"""Adding_foreign_key

Revision ID: 4740f421ff34
Revises: 1a239deca843
Create Date: 2025-11-19 10:47:13.328578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4740f421ff34"
down_revision: Union[str, Sequence[str], None] = "1a239deca843"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("beers", sa.Column("company_id", sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE beers SET company_id = breweries.id FROM breweries where beers.company=breweries.name"
    )
    op.create_foreign_key(None, "beers", "breweries", ["company_id"], ["id"])
    op.create_foreign_key(None, "beers", "breweries", ["company"], ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "beers", type_="foreignkey")
    op.drop_constraint(None, "beers", type_="foreignkey")
    op.drop_column("beers", "company_id")
    # ### end Alembic commands ###
