"""Remove Null Foreign Key

Revision ID: 62978809cb4b
Revises: 4740f421ff34
Create Date: 2025-11-19 10:47:53.815941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '62978809cb4b'
down_revision: Union[str, Sequence[str], None] = '4740f421ff34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beers', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beers', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
