"""Change beer score to float and add default

Revision ID: 92d085a27ca4
Revises: c91a1351dfa9
Create Date: 2025-12-02 12:27:49.142547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '92d085a27ca4'
down_revision: Union[str, Sequence[str], None] = 'c91a1351dfa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beers', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.execute("update beers set score = 0")
    op.execute(
        "update beers set score = t2.avg_score from beers t1 inner join "
        "(Select reviews.beer_id as beer_id, count(*) as total_reviews, avg(reviews.score)::numeric(10,1) as avg_score "
        "from  reviews join beers on reviews.beer_id = beers.id GROUP BY reviews.beer_id) as t2 "
        "on t2.beer_id = t1.id where beers.id = t2.beer_id returning beers.id, beers.score, beers.name"
    )
    op.alter_column('reviews', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('ix_reviews_username'), table_name='reviews')
    op.create_index(op.f('ix_reviews_username'), 'reviews', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_username'), table_name='reviews')
    op.create_index(op.f('ix_reviews_username'), 'reviews', ['username'], unique=True)
    op.alter_column('reviews', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('beers', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
