"""Adding_datetime

Revision ID: 98fa3706f6b5
Revises: a1256e5cd066
Create Date: 2025-11-17 13:24:27.427047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '98fa3706f6b5'
down_revision: Union[str, Sequence[str], None] = 'a1256e5cd066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beers', sa.Column('last_updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('beers', sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beers', 'date_created')
    op.drop_column('beers', 'last_updated')
    # ### end Alembic commands ###
