"""Add_reveiws_table

Revision ID: ad5cf77edbe9
Revises: 62978809cb4b
Create Date: 2025-11-20 09:27:56.950234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ad5cf77edbe9'
down_revision: Union[str, Sequence[str], None] = '62978809cb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('beer_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('score  > 0 AND score <=10', name='check_score_range'),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_comment'), 'reviews', ['comment'], unique=False)
    op.create_index(op.f('ix_reviews_score'), 'reviews', ['score'], unique=False)
    op.create_index(op.f('ix_reviews_username'), 'reviews', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_username'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_score'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_comment'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
