"""Add_beer_name_to_review

Revision ID: c91a1351dfa9
Revises: ad5cf77edbe9
Create Date: 2025-11-20 09:41:56.821609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c91a1351dfa9'
down_revision: Union[str, Sequence[str], None] = 'ad5cf77edbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('beer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_reviews_beer_name'), 'reviews', ['beer_name'], unique=False)
    op.create_foreign_key(None, 'reviews', 'beers', ['beer_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_beer_name'), table_name='reviews')
    op.drop_column('reviews', 'beer_name')
    # ### end Alembic commands ###
